dist: xenial
language: scala

scala:
  - 2.13.1
  - 2.12.10

jdk:
  - openjdk8
script:
  - if [ "$TRAVIS_SCALA_VERSION" = "2.13.1" ]; then sbt checkfmt; fi
  - sbt compile "scalafixAll --check"
  - sbt test
  - if [ "$TRAVIS_SCALA_VERSION" = "2.13.1" ]; then sbt docs/mdoc; fi

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier