dist: xenial
language: scala

scala:
  - 2.13.2
  - 2.12.11

jdk:
  - openjdk8
script:
  - if [ "$TRAVIS_SCALA_VERSION" = "2.13.2" ]; then sbt checkfmt; fi
  - sbt compile
  - sbt test
  - if [ "$TRAVIS_SCALA_VERSION" = "2.13.2" ]; then sbt docs/mdoc; fi

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier