name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  checkfmt:
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v2
     
     - name: Cache jabba
       uses: actions/cache@v2.1.4
       with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}
     
     - name: Cache SBT ivy cache
       uses: actions/cache@v2.1.4
       with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}  
    
     - name: Cache SBT
       uses: actions/cache@v2.1.4
       with:
         path: ~/.sbt
         key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}  
    
     - uses: olafurpg/setup-scala@v10
       with:
         java-version: graalvm-ce-java11@20.3.0
    
     - name: Check format
       run: sbt checkfmt
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.13, 2.13.5]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache jabba
      uses: actions/cache@v2.1.4
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}
      
    - name: Cache SBT ivy cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    
    - name: Cache SBT
      uses: actions/cache@v2.1.4
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: graalvm-ce-java11@20.3.0
    
    - name: Test
      run: sbt ++${{matrix.scala}} test

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actions/checkout@v2

      - name: Cache jabba
        uses: actions/cache@v2.1.4
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jabba-cache-${{ hashFiles('**/workflows/scala.yml') }}

      - name: Cache SBT ivy cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm-ce-java11@20.3.0

      - name: Doc
        run: |
          sbt doc "paradocs/makeSite"


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: master # The branch the action should deploy to.
          folder: docs/target/site

